### ISSUE TITLE
[FE] 회원가입

### ISSUE THREAD

**Issue by alsrl1371** [codestates-seb/seb44_main_036#1]
## 요구사항 ID
MEM-0001
## 요구사항
회원가입
## 상세 요구사항
- 사용자는 회원가입시 판매자와 구매자를 선택해서 가입합니다.
- 이메일, 닉네임, 비밀번호, 비밀번호 확인, (+약관동의)
- 이메일 (이메일 형식 여부를 유효성 검사 합니다.)
- 닉네임 (2자 이상, 10자 이하 특수문자 불가능)
- 비밀번호 유효성 검사 (8자 이상 15자 이하, 특수문자 포함)
- 회원가입 버튼 클릭 시 서버에 POST로 사용자 회원가입 정보를 보낸 후 로그인 페이지로 이동합니다.
- 로그인 페이지로 이동 버튼 클릭 시 로그인 페이지로 이동합니다.
- 이메일 인증(추가구현)
## TODO
- [x] 사용자는 회원가입시 판매자와 구매자를 선택해서 가입합니다.
- [x] 이메일 (이메일 형식 여부를 유효성 검사 합니다.)
- [x] 닉네임 (2자 이상, 10자 이하 특수문자 불가능)
- [x] 비밀번호 유효성 검사 (8자 이상 15자 이하, 특수문자 포함)
- [x] 회원가입 버튼 클릭 시 서버에 POST로 사용자 회원가입 정보를 보낸 후 로그인 페이지로 이동합니다.
- [x] 로그인 페이지로 이동 버튼 클릭 시 로그인 페이지로 이동합니다.
- [ ] 이메일 인증(추가구현)

## 기타 참고사항
3일
