### ISSUE TITLE
[FE] 프로젝트 목록

### ISSUE THREAD

**Issue by hyeincha** [codestates-seb/seb44_main_036#11]
## 요구사항 ID
PRO-003

## 요구사항
모든 사이트 이용자는 메인 페이지에서 프로젝트 목록을 볼 수 있어야 한다.

## 상세 요구사항
- 필수 정보
  - 대표 이미지
  - 좋아요 상태 (비로그인 유저의 경우 false)
  - 프로젝트 제목
  - 달성률
  - 목표 금액
  - 남은 기간

## TODO
- [ ] 카테고리에 따라 다른 프로젝트를 보여줄 수 있어야 한다.
- [ ] 진행중/종료 상태, 최신순, 인기순, 마감임박순으로 정렬할 수 있어야 한다.
- [ ] 비로그인 상태인 경우 좋아요 버튼을 눌렀을 때 로그인이 필요함을 알리는 얼럿이 노출되어야 한다. (확인시 로그인 페이지로 이동)
- [ ] 로그인 상태일 경우 좋아요 버튼으로 좋아요/좋아요 취소가 가능해야 한다.
- [ ] 개별의 프로젝트 클릭시 프로젝트 상세 페이지로 진입해야 한다.
