### ISSUE TITLE
[FE] 프로젝트 펀딩하기

### ISSUE THREAD

**Issue by eyo-25** [codestates-seb/seb44_main_036#14]
## 요구사항 ID
PRO-008

## 요구사항
프로젝트 펀딩하기

## 상세 요구사항
- 기존에 리워드를 선택해서 넘어왔을 경우 리워드가 체크되어 있어야 함
- 리워드 아이디, 수량, 최종금액, 주소 입력해서 폼 제출
- 펀딩 되었습니다! 알럿 노출
- 펀딩 성공시 마이페이지로 이동

## TODO
- [x] 상세에서 선택한 리워드가 활성화
- [x] 리워드 요청사항 제출
- [x] 펀딩 성공 알럿

## 기타 참고사항
2.5 days
