### ISSUE TITLE
[FE] 프로젝트 삭제

### ISSUE THREAD

**Issue by hyeincha** [codestates-seb/seb44_main_036#15]
## 요구사항 ID
PRO-006

## 요구사항
프로젝트 게시자는 자신이 게시한 프로젝트를 삭제할 수 있어야 한다.

## 상세 요구사항
프로젝트 상세 페이지에서 게시자에게만 보이는 삭제 버튼으로 진입

## TODO
- [ ] 삭제 버튼 클릭시 삭제를 확인하는 얼럿 창이 노출되어야 한다.
- [ ] 얼럿에서 확인 버튼 클릭시 삭제 요청을 보내고, 취소 버튼 클릭시 얼럿이 닫히며 페이지가 유지된다.
- [ ] 삭제가 완료되면 삭제 완료를 알리는 토스트가 노출되고, 메인 페이지로 이동해야 한다.
