### ISSUE TITLE
[FE]제목

### ISSUE THREAD

**Issue by eyo-25** [codestates-seb/seb44_main_036#2]
## 요구사항 ID
MY-001

## 요구사항
유저 정보 조회

## 상세 요구사항
- 프로필 사진, 이름, 판매자(서포터/메이커) 구매자(서포터) 계정 구분
- 구매자는 펀딩중인 프로젝트 목록, 내가 좋아요한 프로젝트 목록
- 판매자는 판매중인 프로젝트 목록, 내가 좋아요한 프로젝트 목록
- 로그아웃 버튼 -> 로그아웃
- 프로필 수정 버튼 -> 프로필 수정 모달
- 회원 탈퇴 버튼 -> 클릭시 탈퇴 확인 얼럿 노출 -> 탈퇴 성공시 메인페이지로 이동

## TODO
- [ ] 프로필 정보 표기
- [ ] 회원탈퇴 기능
- [ ] 로그아웃 기능
- [ ] 판매자,구매자에 따른 프로젝트 목록 get해서 렌더링
- [ ] 좋아요한 프로젝트 목록 get해서 렌더링
