### ISSUE TITLE
[BE] 유저 정보 조회

### ISSUE THREAD

**Issue by ihg1130** [codestates-seb/seb44_main_036#23]
## 요구사항 ID
MY-001

## 요구사항
유저 정보 조회

## 상세 요구사항
-프로필 사진, 이름, 판매자(서포터/메이커) 구매자(서포터) 계정 구분
-구매자는 펀딩중인 프로젝트 목록, 내가 좋아요한 프로젝트 목록
-판매자는 판매중인 프로젝트 목록, 내가 좋아요한 프로젝트 목록

## TODO
- [ ] 프로필 정보 표기
- [ ] 회원탈퇴 기능
- [ ] 로그아웃 기능
- [ ] 판매자,구매자에 따른 프로젝트 목록 response
- [ ] 좋아요한 프로젝트 목록 response

## 기타 참고사항
4 days
