### ISSUE TITLE
[BE] 프로젝트 등록

### ISSUE THREAD

**Issue by ihg1130** [codestates-seb/seb44_main_036#25]
## 요구사항 ID
PRO-001

## 요구사항
판매자는 펀딩 프로젝트를 등록할 수 있어야 한다.

## 상세 요구사항
-프로젝트 명: 2자 이상 30자 이내
-대표 이미지: 2MB 이하, jpg, jpeg, png 파일만 허용
-마감일 처리
-목표 금액: 5만원 이상 1천만원 이하
-프로젝트 요약: 최대 100자
-프로젝트 상세: 사진 3장 이하, 내용 혹은 이미지가 존재해야 함
-카테고리: 테크/가전, 패션/잡화, 홈/리빙, 뷰티, 푸드, 스포츠, 컬쳐, 캐릭터/굿즈, 반려동물, 게임/취미, 기타
-태그: 최대 10개, 태그당 최대 10자 이하
-리워드: 1개 이상, 최대 3개까지

## TODO
- [ ] 판매자 계정으로 로그인 했을 때만 프로젝트 생성이 가능해야 함
- [ ] 이미지를 서버에 보냄
- [ ] 프로젝트 생성 요청을 서버에 보내기 전에 상세 요구사항에 기재된 유효성 검사를 수행해야 함
- [ ] 정확한 response 필요

## 기타 참고사항
3일
