### ISSUE TITLE
[FE] 프로젝트 등록

### ISSUE THREAD

**Issue by hyeincha** [codestates-seb/seb44_main_036#3]
## 요구사항 ID
PRO-001

## 요구사항
판매자는 펀딩 프로젝트를 등록할 수 있어야 한다. 

## 상세 요구사항
- 필수 정보 
  - 프로젝트 명: 2자 이상 30자 이내
  - 대표 이미지: 2MB 이하, jpg, jpeg, png 파일만 허용
  - 마감일
  - 목표 금액: 5만원 이상 1천만원 이하
  - 프로젝트 요약: 최대 100자
  - 프로젝트 상세: 사진 3장 이하, 내용 혹은 이미지가 존재해야 함
  - 카테고리: 테크/가전, 패션/잡화, 홈/리빙, 뷰티, 푸드, 스포츠, 컬쳐, 캐릭터/굿즈, 반려동물, 게임/취미, 기타
  - 태그: 최대 10개, 태그당 최대 10자 이하
  - 리워드: 1개 이상, 최대 3개까지

## TODO
- [ ] 판매자 계정으로 로그인 했을 때만 프로젝트 생성이 가능해야 함
- [ ] 이미지를 서버에 보내기 전에 리사이징 해야 함
- [ ] 프로젝트 생성 요청을 서버에 보내기 전에 상세 요구사항에 기재된 유효성 검사를 수행해야 함
- [ ] 생성 요청을 보낸 후 응답이 오기까지 적절한 UI 요소를 보여줘야 함
- [ ] 프로젝트 생성이 완료될 경우 프로젝트 상세 페이지로 이동해야 함
