### ISSUE TITLE
[BE] 프로젝트 상세

### ISSUE THREAD

**Issue by jeonking** [codestates-seb/seb44_main_036#33]
## 요구사항 ID
PRO-002
## 요구사항
프로젝트 상세페이지인 경우 제품명, 이미지, 설명등을 가져올수 있어야함. 
좋아요 기능이 있어야하고 카운팅이 되어야함. 
결제 페이지로 넘어갈 수 있어야함

## 상세 요구사항
- 구매하기 버튼, 상품 선택 버튼
- 상품보기(상품 이미지, 상품명과 설명)/ 본문내용
- 좌측 대표이미지 /우측 프로젝트 스토리
- 우측 카테고리, 태그, 공유, 달성률, D-day, 달성 총 금액, 총 참여자, 좋아요, 펀딩(결제)버튼, 리워드 선택
- 리워드 -> 가격/제품/상세 설명
- 펀딩 버튼이나 리워드 옵션 클릭시 결제페이지로 이동
## TODO
- [ ] 비로그인 유저가 좋아요 혹은 펀딩하기 버튼을 누를시 로그인 페이지로 이동
- [ ] 로그인 유저가 펀딩하기를 누를시 결제페이지 이동
- [ ] 해당 상품의 리워드 내보내기
- [ ] 달성률, 달성금액, 카테고리, 태그정보 내보내기
- [ ] 해당 제품의 이미지 내보내기
