### ISSUE TITLE
[BE]프로젝트 검색

### ISSUE THREAD

**Issue by jeonking** [codestates-seb/seb44_main_036#35]
## 요구사항 ID
PRO-007
## 요구사항
프로젝트 검색
## 상세 요구사항
- 총 검색 결과 개수를 보여준다.
- 정렬 필터링 -> 전체/진행중/종료, 북마크순(인기순), 최신순, 마감임박순
## TODO
- [ ] 총 검색 결과 갯수를 보내준다
- [ ] 필터링 대로 리스트 보내주기
- [ ] 검색 결과 리스트 보내주기
