### ISSUE TITLE
[BE]프로젝트 목록

### ISSUE THREAD

**Issue by jeonking** [codestates-seb/seb44_main_036#38]
## 요구사항 ID
PRO-003
## 요구사항
메인 페이지에서 프로젝트 목록을 볼 수 있어야함.
## 상세 요구사항
- 최신순으로 목록 정렬
- 대표 이미지(+좋아요 버튼), 제목, 달성률, 목표 금액, 남은 기간 
- 카테고리 -> 테크/가전, 패션/잡화, 홈/리빙, 뷰티, 푸드, 스포츠, 컬쳐, 캐릭터/굿즈, 반려동물, 게임/취미, 기타 
- 정렬 필터링 -> 전체/진행중/종료, 북마크순(인기순), 최신순, 마감임박순
## TODO
- [ ] 기본값으로 최신순 목록 정렬
- [ ] 진행중/종료상태를 구분
- [ ] 카테고리별로 목록 불러오기
- [ ] 대표 이미지(+좋아요 버튼), 제목, 달성률, 목표 금액, 남은 기간 불러오기
- [ ] 최신순, 인기순, 마감임박순 목록 정렬
