### ISSUE TITLE
[FE] 프로젝트 상세

### ISSUE THREAD

**Issue by hyeincha** [codestates-seb/seb44_main_036#8]
## 요구사항 ID
PRO-002

## 요구사항
프로젝트 상세 페이지에서는 프로젝트의 상세 정보를 열람할 수 있어야 하며,
좋아요 기능을 제공하며 결제 페이지로 이동할 수 있어야 한다.

## 상세 요구사항
- 필수 정보
  - 대표 이미지
  - 프로젝트 스토리
  - 카테고리
  - 태그
  - 프로젝트 이름
  - 프로젝트 설명
  - 달성률 
  - 달성 금액
  - 좋아요 버튼
  - 펀딩하기 버튼
  - 리워드 목록

## TODO
- [ ] 비로그인 유저가 좋아요를 눌렀을 경우 로그인이 필요한 기능임을 알려야 함
- [ ] 로그인 유저의 경우 좋아요 상태가 좋아요 버튼에 반영되어야 하며, 좋아요 버튼 클릭시 좋아요/좋아요 취소가 가능해야 함
- [ ] 펀딩하기 버튼 클릭시 결제 페이지로 이동해야 함
- [ ] 리워드 클릭시 결제 페이지로 이동하며, 클릭한 리워드가 체크된 상태로 보여져야 함
